kind: pipeline
type: docker
name: build
steps:

  - name: build
    image: library/openjdk:11-jdk
    commands:
      - ./gradlew clean build


  - name: docker-build-publish
    image: plugins/docker
    dockerfile: Dockerfile
    settings:
      repo: just-a-coder/dockerkubernetesapp
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: kubernetes-deploy
    image: sinlead/drone-kubectl
    commands:
      - echo "Line1"
#      - kubectl get pods
      - echo "Line2b"
      - kubectl apply --filename kubernetes/deployment.yaml
      - echo "Line2"
#      - kubectl apply --context minikube --filename src/main/kubernetes/service.yaml
#      - echo "Line3"
#      - kubectl apply --context minikube --filename src/main/kubernetes/ingress.yaml
#      - echo "Line4"