pipeline:
  build:
    when:
      branch: develop
      event: push
    image: openjdk:11-jdk
    commands:
      - ./gradlew build
  docker-build-publish:
    when:
      branch: develop
      event: push
    image: plugins/docker
    settings:
      repo: just-a-coder/dockerkubernetesapp
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    Dockerfile: src/main/docker/Dockerfile

  kubernetes-deploy:
    when:
      branch: develop
      event: push
    image: brianberzins/kubectl:latest
    commands:
      - kubectl get pods
      - kubectl apply --filename kubernetes/deployment.yaml
      - kubectl apply --filename kubernetes/service.yaml
      - kubectl apply --filename kubernetes/ingress.yaml