kind: pipeline
type: docker
name: build
steps:

  - name: build
    image: library/openjdk:11-jdk
    commands:
      - ./gradlew clean build

  - name: publish
    image: plugins/docker
    settings:
      repo: just-a-coder/dockerkubernetesapp
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: deploy
    image: docker
    commands:
      - kubectl run test-deploy --image= docker --port=8080


