kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: alpine
    commands:
      - echo hello
      - echo world
  -build:
      image: library/openjdk:8-jdk
      commands:
        - ./gradlew clean build
