kind: pipeline
type: docker
name: build
steps:

  - name: build
    image: library/openjdk:11-jdk
    commands:
      - ./gradlew clean build

  - name: docker
    image: plugins/docker
    environment:
      repo: just-a-coder/dockerkubernetesapp
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    tag:
      - "${DRONE_COMMIT:0:8}"
    when:
      branch: [develop, master]
      event: push
  

