pipeline:
  build:
    when:
      branch: develop
      event: push
    image: openjdk:11-jdk
    commands:
      - ./gradlew clean build

  docker-build-publish:
    when:
      branch: develop
      event: push
    image: plugins/docker
    settings:
      repo: just-a-coder/dockerkubernetesapp
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    dockerfile: Dockerfile
    commands:
      - echo "line1"
    tag: latest

  kubernetes-deploy:
    when:
      branch: develop
      event: push
    image: brianberzins/kubectl:latest
    commands:
      - echo "line11"
      - kubectl get pods
      - echo "line12"
      - kubectl apply --filename kubernetes/deployment.yaml
      - echo "line13"
      - kubectl apply --filename kubernetes/service.yaml
      - echo "line14"
      - kubectl apply --filename kubernetes/ingress.yaml
      - echo "line15"