apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minikube-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minikube-deploy
    spec:
      containers:
        - name: minikube-deploy
          image: justacoder7/dockerkubernetesapp
          ports:
            - containerPort: 8080